//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiTeam.ColorfulIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiTeam.ColorfulIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Image Files(*.BMP;*.JPG;*.GIF;*.PNG)|*.BMP;*.JPG;*.GIF;*.PNG 的本地化字符串。
        /// </summary>
        public static string BrowseSingleFile_EditValue_Image_Files___BMP___JPG___GIF___PNG____BMP___JPG___GIF___PNG {
            get {
                return ResourceManager.GetString("BrowseSingleFile_EditValue_Image_Files___BMP___JPG___GIF___PNG____BMP___JPG___GIF" +
                        "___PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string menuName {
            get {
                return ResourceManager.GetString("menuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsDirectory 的本地化字符串。
        /// </summary>
        public static string S208 {
            get {
                return ResourceManager.GetString("S208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether you want to set the image path or directory. 的本地化字符串。
        /// </summary>
        public static string S210 {
            get {
                return ResourceManager.GetString("S210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageFilePath 的本地化字符串。
        /// </summary>
        public static string S212 {
            get {
                return ResourceManager.GetString("S212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where you want your image to show. 的本地化字符串。
        /// </summary>
        public static string S214 {
            get {
                return ResourceManager.GetString("S214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Directory 的本地化字符串。
        /// </summary>
        public static string S216 {
            get {
                return ResourceManager.GetString("S216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where you want your images to show. 的本地化字符串。
        /// </summary>
        public static string S218 {
            get {
                return ResourceManager.GetString("S218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity 的本地化字符串。
        /// </summary>
        public static string S220 {
            get {
                return ResourceManager.GetString("S220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Opacity of the background image. (the value is between 0.00 and 1.00) 的本地化字符串。
        /// </summary>
        public static string S222 {
            get {
                return ResourceManager.GetString("S222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal Position 的本地化字符串。
        /// </summary>
        public static string S224 {
            get {
                return ResourceManager.GetString("S224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the horizontal position of the background image. 的本地化字符串。
        /// </summary>
        public static string S226 {
            get {
                return ResourceManager.GetString("S226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Position 的本地化字符串。
        /// </summary>
        public static string S228 {
            get {
                return ResourceManager.GetString("S228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the vertical position of the background image. 的本地化字符串。
        /// </summary>
        public static string S230 {
            get {
                return ResourceManager.GetString("S230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval 的本地化字符串。
        /// </summary>
        public static string S232 {
            get {
                return ResourceManager.GetString("S232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time between each image change(the unit is milliseconds). 的本地化字符串。
        /// </summary>
        public static string S234 {
            get {
                return ResourceManager.GetString("S234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpacityInterval 的本地化字符串。
        /// </summary>
        public static string S236 {
            get {
                return ResourceManager.GetString("S236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time between each opacity change(the unit is milliseconds). 的本地化字符串。
        /// </summary>
        public static string S238 {
            get {
                return ResourceManager.GetString("S238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChangeBackgroundColor 的本地化字符串。
        /// </summary>
        public static string S240 {
            get {
                return ResourceManager.GetString("S240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Judging that whether the background color of the editor changes with the picture&apos;s. 的本地化字符串。
        /// </summary>
        public static string S242 {
            get {
                return ResourceManager.GetString("S242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoResize 的本地化字符串。
        /// </summary>
        public static string S244 {
            get {
                return ResourceManager.GetString("S244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Judging that whether the background will be auto-resized if the size of  the picture is larger than the editor window.  的本地化字符串。
        /// </summary>
        public static string S246 {
            get {
                return ResourceManager.GetString("S246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RandomSequence 的本地化字符串。
        /// </summary>
        public static string S248 {
            get {
                return ResourceManager.GetString("S248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Judging that whether the background images will be shown following a pattern or randomly. 的本地化字符串。
        /// </summary>
        public static string S250 {
            get {
                return ResourceManager.GetString("S250", resourceCulture);
            }
        }
    }
}
